name: safe_manager
description: Frave Developer projects.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.3.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_secure_storage: ^7.0.1
  google_fonts: ^3.0.1
  flutter_windowmanager: ^0.2.0
  local_auth: ^2.1.2
  encrypt: ^5.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.7
  flutter_svg: ^1.1.6
  uuid: ^3.0.7
  timeago: ^3.3.0
  card_swiper: ^2.0.4
  intl: 0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/logos/
  #   - images/a_dot_ham.jpeg

  # fonts:
    # - family: Poppins
    #   fonts:
    #     - asset: fonts/Poppins/Poppins-Bold.ttf
    #     - asset: fonts/Poppins/Poppins-Regular.ttf
  #         style: italic
    # - family: Roboto
    #   fonts:
    #     - asset: fonts/Roboto/Roboto-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
